<?php

/**
 * Implementation of hook_menu().
 */
function internet_devels_menu() {
  $items = array();
  $items['internet_devels_page'] = array(
    'title'           => '', 
    'page callback'   => 'internet_devels_page',
    'type'            => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}

function internet_devels_preprocess_page(&$vars) {

  //if (isset($vars['node']->title) {
  //  $vars['node']->title = '';
  //}
 $vars['breadcrumb'] = '';
 
//drupal_set_message('<pre><strong>debug:</strong><br />' . print_r($vars, 1) . '</pre>', 'warning');
}

function internet_devels_page() {
  print '';
  return ' ';
}
